### ISSUE TITLE
Some files are not bundled

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/demo-kendo#1]
![image](https://cloud.githubusercontent.com/assets/2189477/11453712/bbd04df2-9615-11e5-993e-590d6fe64c53.png)

**Comment by adriatic** [comment]
I believe that all future KendoUI issues should be reported [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/issues) as the [demo-kendo application](https://github.com/aurelia-ui-toolkits/demo-kendo) is the derivative of the [sample](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-plugin/tree/master/sample) application - and as such all the fixes have to reported accordingly.

Agreed?

**Comment by JeroenVinke** [comment]
I agree, that way we can also assign them to a milestone to know that we need to close the issue before releasing
