### ISSUE TITLE
coordinates display shows no data

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/demo-kendo#10]
![image](https://cloud.githubusercontent.com/assets/2712405/24830044/ed5d97b8-1c4b-11e7-9bdf-4bac17756653.png)

**Comment by JeroenVinke** [comment]
I wonder, what are you expecting to see? Those spots seem to be outside of the chart

**Comment by adriatic** [comment]
It is easier to say what I do not expect to see: those **empty** while panels. However, not to leave any space for a miscommunication, here is what I xpect to see:

![image](https://cloud.githubusercontent.com/assets/2712405/24831842/33e28468-1c70-11e7-952b-b70619a60207.png)

**Comment by JeroenVinke** [comment]
Aha!
