### ISSUE TITLE
Toolbar'a imports section incomplete

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/demo-kendo#20]
See **[`Integration with editors`](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/toolbar-integration-with-editors)** sample:

![image](https://user-images.githubusercontent.com/2712405/28505377-418fecac-6ff1-11e7-83d0-639151df62b0.png)

versus actual code in **`app.html`**
```
  <require from="./integration-with-editors.css!css"></require>
  <require from="aurelia-kendoui-bridge/toolbar/toolbar"></require>
  <require from="aurelia-kendoui-bridge/toolbar/toolbar-item"></require>
  <require from="aurelia-kendoui-bridge/toolbar/toolbar-item-button"></require>
  <require from="aurelia-kendoui-bridge/dropdownlist/dropdownlist"></require>
  <require from="aurelia-kendoui-bridge/numerictextbox/numerictextbox"></require>
  <require from="aurelia-kendoui-bridge/colorpicker/colorpicker"></require>
  <require from="aurelia-kendoui-bridge/common/template"></require>

```

**Comment by JeroenVinke** [comment]
The require tags in the popup are the ones you need for that specific control. The ones in the sample's HTML are the ones you need to run that sample.

**Comment by adriatic** [comment]
Despite my initial view of this, I have to agree with you 😄
