### ISSUE TITLE
Aurelia Dropdown custom template demo is broken

### ISSUE THREAD

**Issue by th3mon** [aurelia-ui-toolkits/demo-kendo#9]
Hi!

Kendo UI Professional Sorry for disturbing but [Aurelia dropdown demo](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/dropdownlist-customizing-templates) is broken.

**Comment by JeroenVinke** [comment]
Hi!

I am taking a look at this today. Keep an eye on https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/733 where I will post updates.
